version: "3.6"
services:
  webserver:
    image: nginx:latest
    restart: unless-stopped
    container_name: laravel_docker_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - $PWD:/var/www/html
    ports:
      - 9898:80
    networks:
      - applaravel
  app:
    build: .
    restart: unless-stopped
    container_name: laravel_docker_php
    volumes:
      - $PWD:/var/www/html
    networks: 
      - applaravel
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_ROOT_PASSWORD: adminlocal
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - applaravel
networks:
  applaravel:
    driver: bridge
volumes:
  dbdata: